server.port: 8080
welcome.message: "hello09"
transfer-benefits:
  partner:
    ua:
      communication: 
        type: Rest
        postCurrency:
          method: Post
          header:
            requestMapping:
              - attribute: Content-Type
                type: string
                refer: env-variable
                value: application/json
              - attribute: Authorization
                type: string
                refer: jsonPath
                value: $.partnerAdditionalReqAttribs.access_token
          body:
            etpben:
            bentype:
          url: ${UA_MILES_DEPOSIT_URL:https://ggogle.com}
          responseMapping:
            error: "$.Errors[?(@.UserFriendlyMessage)].UserFriendlyMessage"
          postProcessing:
            - removalAttribute: benefits
              checkAttribute: benefitAmount
              expectedValue: 0
